// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_user_by_file_name.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT name FROM users WHERE name = $1
`

func (q *Queries) GetUser(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	err := row.Scan(&name)
	return name, err
}
