// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: unfollow_feed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const unFollowFeed = `-- name: UnFollowFeed :exec
DELETE FROM feed_follows WHERE user_id = $1 AND feed_id = $2
`

type UnFollowFeedParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) UnFollowFeed(ctx context.Context, arg UnFollowFeedParams) error {
	_, err := q.db.ExecContext(ctx, unFollowFeed, arg.UserID, arg.FeedID)
	return err
}
